--------------------------------------------------------
--  File created - Friday-May-05-2017   
--------------------------------------------------------
REM INSERTING into C##DELIUSAPI.R_CONTACT_TYPE
SET DEFINE OFF;
Insert into C##DELIUSAPI.R_CONTACT_TYPE (CONTACT_TYPE_ID,CODE,DESCRIPTION,SHORT_DESCRIPTION,SELECTABLE,NATIONAL_STANDARDS_CONTACT,ATTENDANCE_CONTACT,RECORDED_HOURS_CREDITED,SENSITIVE_CONTACT,OFFENDER_LEVEL_CONTACT,ROW_VERSION,CREATED_DATETIME,APPEARS_IN_LIST_OF_CONTACTS,SMS_MESSAGE_TEXT,OFFENDER_EVENT_0,LEGACY_ORDERS,LAST_UPDATED_DATETIME,CJA_ORDERS,DPA_EXCLUDE,TRAINING_SESSION_ID,CONTACT_OUTCOME_FLAG,CONTACT_LOCATION_FLAG,CREATED_BY_USER_ID,CONTACT_ALERT_FLAG,LAST_UPDATED_USER_ID,FUTURE_SCHEDULED_CONTACTS_FLAG,CONTACT_TYPE_ICON_ID,EDITABLE,PSS_RQMNT,RAR_ACTIVITY,SPG_OVERRIDE,NOMIS_CONTACT_TYPE) values (1,'X',' nomis case noteA',null,'Y',null,null,null,null,null,0,to_date('04-MAY-17','DD-MON-RR'),null,null,null,null,to_date('04-MAY-17','DD-MON-RR'),null,null,null,'Y','Y',1,'X',1,null,null,null,null,null,null,'nomisNoteType');
