REM INSERTING into STAFF
SET DEFINE OFF;
Insert into STAFF (STAFF_ID,START_DATE,SURNAME,END_DATE,FORENAME,ROW_VERSION,FORENAME2,STAFF_GRADE_ID,TITLE_ID,OFFICER_CODE,CREATED_BY_USER_ID,LAST_UPDATED_USER_ID,CREATED_DATETIME,LAST_UPDATED_DATETIME,TRAINING_SESSION_ID,PRIVATE,SC_PROVIDER_ID,PROBATION_AREA_ID) values (1,to_date('01-MAY-17','DD-MON-RR'),'Mackaye',null,'Fulton',0,null,null,null,'xxxxxU ',1,1,to_date('01-MAY-17','DD-MON-RR'),to_date('01-MAY-17','DD-MON-RR'),null,0,null,1);
