REM INSERTING into TEAM
SET DEFINE OFF;
Insert into TEAM (TEAM_ID,CODE,DESCRIPTION,DISTRICT_ID,LOCAL_DELIVERY_UNIT_ID,TELEPHONE,UNPAID_WORK_TEAM,ROW_VERSION,FAX_NUMBER,CONTACT_NAME,START_DATE,END_DATE,CREATED_DATETIME,CREATED_BY_USER_ID,LAST_UPDATED_DATETIME,LAST_UPDATED_USER_ID,TRAINING_SESSION_ID,PROBATION_AREA_ID,PRIVATE,SC_PROVIDER_ID) values (1,'xxxUAT','x',1,1,null,'N',0,null,null,to_date('01-MAY-17','DD-MON-RR'),null,to_date('01-MAY-17','DD-MON-RR'),1,to_date('01-MAY-17','DD-MON-RR'),1,null,1,0,null);
