REM INSERTING into STAFF_TEAM
SET DEFINE OFF;
Insert into STAFF_TEAM (STAFF_ID,TEAM_ID,ROW_VERSION,CREATED_BY_USER_ID,CREATED_DATETIME,LAST_UPDATED_USER_ID,LAST_UPDATED_DATETIME,TRAINING_SESSION_ID) values (1,1,0,1,to_date('01-MAY-17','DD-MON-RR'),1,to_date('01-MAY-17','DD-MON-RR'),null);
